Repository QuiltMC/rfcs, pull requests merged in 2023-06, with the labels that each got.

#78 RFC 0007: Reduce vote length to 3 days
  structure/0007-community-team.md
Labels: final-comment

#80 RFC 0001: Modernize the RFC process
  structure/0001-rfc-process.md
Labels: final-comment, amendment

#81 RFC 0081: Active User Beacon
  specification/0081-active-user-beacon.md
Labels: final-comment, loader

#56 RFC 0056: Permit multiple version constraints in a single version specifier.
  specification/0002-quilt.mod.json.md
Labels: final-comment, loader
